language: node_js
node_js:
  - '12'
  - '10'
  - '9'
install:
  - npm install
os:
  - linux
 
stages:
  - name: deploy # 调用指定deploy命令
 
jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."
 
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - npm run build
        - echo "NPM Building Finished."
 
      deploy:
        provider: npm
        email: chen742068070@163.com
        api_key: '$NPM_TOKEN' # 使用变量读取
        skip_cleanup: true
        # 触发deploy命令条件
        on:
          branch: master # 指定监听分支号